### ISSUE TITLE
NPM Support?

### ISSUE THREAD

**Issue by ryanzec** [callmehiphop/backend#10]
I use browserify for my client side coding and since then I have moved away from using bower and just sticking with npm for installing all dependencies (having one tool is better than 2 tools for managing dependencies).  Now the code here is already written in a CommonJS style so I think making this available on NPM should not be terribly hard, I imagine it is just tweaking the package.json file and just testing.

If this is something you think is a good idea and be willing to accept as a PR, I would probably be able to find some time either this weekend or next to give it a go.  What do you think?

**Comment by ryanzec** [comment]
This is actually dead simple, I just added the `main` property to the json file and installing it from my local directory, everything works fine.  Probably just need a .npmignore file, updates to the READ ME, and a different name since backend it already taken on npm (maybe `mocked-backend` or `client-backend`).

If you do want this PR, just let me know what name I should use in the package.json file.

**Comment by callmehiphop** [comment]
This sounds like an awesome suggestion to me! If you have the time a PR would be welcomed, otherwise I can find the time to do it today/tomorrow.

**Comment by ryanzec** [comment]
Added pull request #11.  Used the name `mocked-backend` for npm but left bower name the same to prevent existing stuff from breaking, not sure if you wanted the bower name changed too.  added .npmignore to ignore stuff not needed for into and added an installation section to the read me.

**Comment by ryanzec** [comment]
Added a bug fix to that PR where when trying to match a mock, it was trying to match an object to a JSON string for the request data.

**Comment by callmehiphop** [comment]
closed per #11
