### ISSUE TITLE
Use lodash modules from npm

### ISSUE THREAD

**Issue by stephenplusplus** [callmehiphop/backend#14]
Instead of packaging a custom build, you can just use the pieces you need from npm, such as https://www.npmjs.com/package/lodash.ismatch

**Comment by callmehiphop** [comment]
yeah, that's a good suggestion. I was only doing a custom build since backend uses a small handful of lodash.

**Comment by stephenplusplus** [comment]
:+1: And this is just the npm way of doing it!

**Comment by callmehiphop** [comment]
After running browserify it went from 2000 lines to 12000 lines, lol.

**Comment by stephenplusplus** [comment]
WAT.

Don't forget the new lodash build with _isMatch is ~3400 lines, which should make your browserified bundle a little larger than the 2k  it is currently.

Still, though. Not sure how it went up that much :\
