### ISSUE TITLE
npm version 0.2.5 broken

### ISSUE THREAD

**Issue by ryanzec** [callmehiphop/backend#17]
For some reason, the latest version (0.2.5) in npm does not install with the index.js file so it could load the module.

**Comment by callmehiphop** [comment]
Not really sure what happened, but it might be related to this https://github.com/npm/npm/issues/5082.
Bumped the version to v0.2.6 and the index.js file is showing up now

**Comment by stephenplusplus** [comment]
That was weird.

**Comment by callmehiphop** [comment]
@stephenplusplus sure was D:
