### ISSUE TITLE
verifyNoOutstandingExpectations and expect API

### ISSUE THREAD

**Issue by nathanboktae** [callmehiphop/backend#20]
One of the most powerful features of $httpBackend was the `expectGET` family of APIs that would assert that a call would happen and only once. Sure there's no `$digest` cycle (thank god) but we can do the assertions on `verifyNoOutstandingExpectations` and `verifyNoOutstandingRequests` during our test cleanup.

**Comment by callmehiphop** [comment]
I agree! I could probably get these in sometime over the weekend, unless you'd like to prepare an PR! Thanks for opening this!

**Comment by nathanboktae** [comment]
Yup cool I might, hmmm....

**Comment by callmehiphop** [comment]
Closed per https://github.com/callmehiphop/backend/pull/24
