### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mateatslc** [callmehiphop/backend#25]
Can you please release a new version to npm? Lots of important changes in since v0.3.1.

**Comment by callmehiphop** [comment]
Yep, I'll work on that this week, I'd like to get https://github.com/callmehiphop/backend/pull/21 resolved first.

**Comment by mateatslc** [comment]
cool, i'll hang tight!

**Comment by callmehiphop** [comment]
Later than I promised, but v0.4.0 is published!

**Comment by mateatslc** [comment]
cool, thanks!
